USE [master]
GO
/****** Object:  Database [TestDB1]    Script Date: 26.5.2022. 18:56:41 ******/
CREATE DATABASE [TestDB1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TestDB1', FILENAME = N'C:\Users\ibudi\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\TestDB1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TestDB1_log', FILENAME = N'C:\Users\ibudi\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\TestDB1.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [TestDB1] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TestDB1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TestDB1] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [TestDB1] SET ANSI_NULLS ON 
GO
ALTER DATABASE [TestDB1] SET ANSI_PADDING ON 
GO
ALTER DATABASE [TestDB1] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [TestDB1] SET ARITHABORT ON 
GO
ALTER DATABASE [TestDB1] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TestDB1] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TestDB1] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TestDB1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TestDB1] SET CURSOR_DEFAULT  LOCAL 
GO
ALTER DATABASE [TestDB1] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [TestDB1] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TestDB1] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [TestDB1] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TestDB1] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TestDB1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TestDB1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TestDB1] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TestDB1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TestDB1] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TestDB1] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TestDB1] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TestDB1] SET RECOVERY FULL 
GO
ALTER DATABASE [TestDB1] SET  MULTI_USER 
GO
ALTER DATABASE [TestDB1] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TestDB1] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TestDB1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TestDB1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TestDB1] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TestDB1] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [TestDB1] SET QUERY_STORE = OFF
GO
USE [TestDB1]
GO
/****** Object:  Table [dbo].[LeftData]    Script Date: 26.5.2022. 18:56:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LeftData](
	[Id] [int] NOT NULL,
	[LeftValue] [varchar](150) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RightData]    Script Date: 26.5.2022. 18:56:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RightData](
	[Id] [int] NOT NULL,
	[RightValue] [varchar](150) NOT NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [TestDB1] SET  READ_WRITE 
GO
